name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install matplotlib
        pip install pytelegrambotapi
        pip install requests
        pip install numpy

    - name: Run Pylint
      run: |
        pylint main.py
        pylint tests/first_test.py

    - name: Testing the code
      run:  python3 tests/first_test.py
