name: CD


on:

  push:
    tags:
      - 'v*'
  release:
    types:
      - created


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install numpy
          pip install matplotlib
          pip install requests
          pip install pytelegrambotapi

      - name: Run Pylint
        run: |
          pylint main.py
          pylint tests/first_test.py

      - name: Testing code
        run:  python3 tests/first_test.py

      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/simplewhale:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
